databases:
  - name: most-db
    databaseName: most
    user: most
    plan: free
    region: frankfurt

services:
  - type: web
    name: most-api
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: frankfurt
    envVars:
      - key: PGHOST
        fromDatabase:
          name: most-db
          property: host
      - key: PGPORT
        fromDatabase:
          name: most-db
          property: port
      - key: PGDATABASE
        fromDatabase:
          name: most-db
          property: database
      - key: PGUSER
        fromDatabase:
          name: most-db
          property: user
      - key: PGPASSWORD
        fromDatabase:
          name: most-db
          property: password
      - key: JWT_SECRET
        generateValue: true
